#!/bin/bash

output_file="classwork_analysis.txt"
> "$output_file"

# iterates through repo in current working directory and runs a git log
for repo in */; do
    if [ -d "$repo" ]; then  # Check if it's a directory
        # only includes author name, commit message, and only commits since date and until date
        git -C "$repo" log --oneline --format="%an : %s" --since="2023-11-17 13:00:00" --until="2023-11-17 15:00:00" >> "$output_file"
        echo "" >> "$output_file"
    fi
done

cat "$output_file"