#!/bin/bash

# asks user for number and stores it in UNIT_NUM
echo "Unit number: "
read UNIT_NUM

#FULL_NUM = $(printf "%.2f" $UNIT_NUM)
echo 

#unit_dir="/c/Users/esthe/CASoftDevI/unit$UNIT_NUM"

#if [ -d $unit_dir ]; then

#	cd $unit_dir
#	pwd
